services:
    api:
        build: ./api
        ports:
            - '8080:8080'
        volumes:
            - ./api:/usr/src/app

    web:
        build:
            context: ./web
            args:
                - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
        ports:
            - '3000:3000'
        volumes:
            - ./web:/usr/src/app
        depends_on:
            - api
