services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file: ./.env.dev
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
        networks:
            - backend

    api:
        build: ./api
        ports:
            - '8080:8080'
        volumes:
            - ./api:/usr/src/app
        environment:
            - DB_HOST=mysqldb
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_DOCKER_PORT
            - CLIENT_ORIGIN=$CLIENT_ORIGIN
        networks:
            - frontend
            - backend

    web:
        build:
            context: ./web
            args:
                - API_BASE_URL=$CLIENT_API_BASE_URL
        ports:
            - '3000:3000'
        volumes:
            - ./web:/usr/src/app
        depends_on:
            - api
        networks:
            - frontend

networks:
    backend:
    frontend:
